# Builds docs/src/parameters.md, a reference table of every parameter in the
# bundled default file, grouped by the section comments of parameters.toml.
#
# The section comments are the only grouping the TOML file carries, and
# TOML.parse discards comments, so the file is scanned line by line.

import ClimaParams
import TOML

"""
    parse_sections(filepath)

Return `(level, title, [parameter_name, ...])` tuples, in file order, by scanning
the comment headers and table headers of the TOML file at `filepath`.

`parameters.toml` uses `##` comments for top-level groups and `#` comments for
the subsections within them. A heading is set off by a blank line; a comment
written directly above a parameter is a note about that parameter and is not
treated as a heading.
"""
function parse_sections(filepath)
    sections = Tuple{Int, String, Vector{String}}[]
    current = (1, "Uncategorized", String[])
    lines = readlines(filepath)
    for (i, line) in enumerate(lines)
        stripped = strip(line)
        if startswith(stripped, "#")
            following = i < length(lines) ? strip(lines[i + 1]) : ""
            isempty(following) || continue
            level = startswith(stripped, "##") ? 1 : 2
            title = strip(lstrip(stripped, ['#', ' ']))
            isempty(title) && continue
            # A top-level group whose parameters all live in subsections still
            # gets a heading, so the nesting survives; the leading placeholder
            # does not.
            (current[2] == "Uncategorized" && isempty(last(current))) ||
                push!(sections, current)
            current = (level, title, String[])
        elseif startswith(stripped, "[") && endswith(stripped, "]")
            # Keys with non-ASCII characters are quoted in TOML.
            push!(last(current), strip(strip(stripped, ['[', ']']), '"'))
        end
    end
    isempty(last(current)) || push!(sections, current)
    return sections
end

"""
    escape_prose(text)

Escape the characters that markdown would otherwise read as formatting inside a
table cell.

`|` ends the cell. `_` and `*` pair up across the whole cell, so two unrelated
identifiers italicize the text between them: `'carbon_dioxide_GM'` renders as
`carbon<em>dioxide</em>GM`.
"""
escape_prose(text) = replace(text, "|" => "\\|", "_" => "\\_", "*" => "\\*")

"""
    format_description(description)

Convert a TOML `description` into markdown that Documenter can render in a table
cell.

A description is a sequence of three kinds of span: `\$...\$` math, `` `...` ``
code, and the prose between them. Math becomes Documenter's double-backtick
inline math and is passed through unaltered, since its contents are LaTeX. Code
spans keep their contents, since markdown does not format inside them. Only the
prose is escaped, by [`escape_prose`](@ref).
"""
function format_description(description)
    out = IOBuffer()
    span = IOBuffer()
    mode = :prose
    for c in description
        if mode === :prose && (c == '$' || c == '`')
            print(out, escape_prose(String(take!(span))))
            mode = c == '$' ? :math : :code
        elseif mode === :math && c == '$'
            math = String(take!(span))
            # A `|` here cannot be both escaped for the table and left alone for
            # KaTeX, which reads `\\|` as the norm delimiter.
            occursin('|', math) && error(
                "`|` in math is not representable in a table cell; " *
                "use `\\\\vert` instead: $description",
            )
            print(out, "``", math, "``")
            mode = :prose
        elseif mode === :code && c == '`'
            print(out, '`', replace(String(take!(span)), "|" => "\\|"), '`')
            mode = :prose
        else
            print(span, c)
        end
    end
    mode === :prose ||
        error("Unterminated $mode span in description: $description")
    print(out, escape_prose(String(take!(span))))
    return String(take!(out))
end

"""
    format_value(value)

Render a parameter value for a table cell, truncating long arrays.
"""
function format_value(value)
    value isa AbstractVector || return string("`", value, "`")
    length(value) <= 4 && return string("`", value, "`")
    head = join(value[1:3], ", ")
    return string("`[", head, ", …]` (", length(value), " entries)")
end

function generate_parameter_table(toml_path, output_path)
    data = TOML.parsefile(toml_path)
    sections = parse_sections(toml_path)

    open(output_path, "w") do io
        println(
            io,
            """
```@meta
CurrentModule = ClimaParams
```

# Parameter List

Every parameter in the default file bundled with ClimaParams.jl
(`src/parameters.toml`), grouped by the sections of that file. This page
is generated by the documentation build, so it cannot drift from the file
it documents.

Retrieve any of these by name:

```julia
import ClimaParams as CP
toml_dict = CP.create_toml_dict(Float64)
toml_dict["gravitational_acceleration"]
```

See [Adding and Changing Parameters](@ref) to add one.
""",
        )

        n_groups = count(section -> first(section) == 1, sections)
        println(
            io,
            "There are $(length(data)) parameters in $n_groups groups.\n",
        )

        for (level, title, names) in sections
            println(io, "#"^(level + 1), " ", title, "\n")
            if isempty(names)
                continue
            end
            println(io, "| Name | Value | Type | Description |")
            println(io, "|:-----|:------|:-----|:------------|")
            for name in names
                entry = data[name]
                description = format_description(get(entry, "description", ""))
                println(
                    io,
                    "| `",
                    name,
                    "` | ",
                    format_value(entry["value"]),
                    " | ",
                    entry["type"],
                    " | ",
                    description,
                    " |",
                )
            end
            println(io)
        end
    end
    return output_path
end

generate_parameter_table(
    joinpath(pkgdir(ClimaParams), "src", "parameters.toml"),
    joinpath(@__DIR__, "src", "parameters.md"),
)
